// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "App": {
      /**
       * CheckForUpdates
       * @returns {Promise<boolean>}  - Go Type: bool
       */
      "CheckForUpdates": () => {
        return window.go.main.App.CheckForUpdates();
      },
      /**
       * GetEntityNamesWithLineHighlightingColors
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetEntityNamesWithLineHighlightingColors": () => {
        return window.go.main.App.GetEntityNamesWithLineHighlightingColors();
      },
      /**
       * GetFilters
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetFilters": () => {
        return window.go.main.App.GetFilters();
      },
      /**
       * GetLogs
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetLogs": () => {
        return window.go.main.App.GetLogs();
      },
      /**
       * GetOtherFileContent
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetOtherFileContent": (arg1) => {
        return window.go.main.App.GetOtherFileContent(arg1);
      },
      /**
       * GetRunningIDEsDropdownHTML
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetRunningIDEsDropdownHTML": () => {
        return window.go.main.App.GetRunningIDEsDropdownHTML();
      },
      /**
       * GetSetting
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<number>}  - Go Type: interface {}
       */
      "GetSetting": (arg1) => {
        return window.go.main.App.GetSetting(arg1);
      },
      /**
       * GetSettingsScreenHTML
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetSettingsScreenHTML": () => {
        return window.go.main.App.GetSettingsScreenHTML();
      },
      /**
       * GetStaticInfo
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetStaticInfo": () => {
        return window.go.main.App.GetStaticInfo();
      },
      /**
       * GetSummary
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetSummary": () => {
        return window.go.main.App.GetSummary();
      },
      /**
       * GetThreadDumpFileContent
       * @param {string} arg1 - Go Type: string
       * @param {string} arg2 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetThreadDumpFileContent": (arg1, arg2) => {
        return window.go.main.App.GetThreadDumpFileContent(arg1, arg2);
      },
      /**
       * GetThreadDumpsFilters
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetThreadDumpsFilters": (arg1) => {
        return window.go.main.App.GetThreadDumpsFilters(arg1);
      },
      /**
       * InitLogDirectory
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "InitLogDirectory": (arg1) => {
        return window.go.main.App.InitLogDirectory(arg1);
      },
      /**
       * OpenArchive
       * @returns {Promise<string>}  - Go Type: string
       */
      "OpenArchive": () => {
        return window.go.main.App.OpenArchive();
      },
      /**
       * OpenFolder
       * @returns {Promise<string>}  - Go Type: string
       */
      "OpenFolder": () => {
        return window.go.main.App.OpenFolder();
      },
      /**
       * OpenIndexingReport
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<void>} 
       */
      "OpenIndexingReport": (arg1) => {
        return window.go.main.App.OpenIndexingReport(arg1);
      },
      /**
       * OpenIndexingSummaryForProject
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<void>} 
       */
      "OpenIndexingSummaryForProject": (arg1) => {
        return window.go.main.App.OpenIndexingSummaryForProject(arg1);
      },
      /**
       * RenderSystemMenu
       * @returns {Promise<void>} 
       */
      "RenderSystemMenu": () => {
        return window.go.main.App.RenderSystemMenu();
      },
      /**
       * SaveSetting
       * @param {string} arg1 - Go Type: string
       * @param {number} arg2 - Go Type: interface {}
       * @returns {Promise<void>} 
       */
      "SaveSetting": (arg1, arg2) => {
        return window.go.main.App.SaveSetting(arg1, arg2);
      },
      /**
       * SetFilters
       * @param {any} arg1 - Go Type: map[string]bool
       * @returns {Promise<string>}  - Go Type: string
       */
      "SetFilters": (arg1) => {
        return window.go.main.App.SetFilters(arg1);
      },
      /**
       * ShowNoUpdatesMessage
       * @returns {Promise<void>} 
       */
      "ShowNoUpdatesMessage": () => {
        return window.go.main.App.ShowNoUpdatesMessage();
      },
      /**
       * UploadArchive
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "UploadArchive": (arg1) => {
        return window.go.main.App.UploadArchive(arg1);
      },
      /**
       * UploadLogFile
       * @param {string} arg1 - Go Type: string
       * @param {string} arg2 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "UploadLogFile": (arg1, arg2) => {
        return window.go.main.App.UploadLogFile(arg1, arg2);
      },
    },
  },

};
export default go;
