// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "App": {
      /**
       * FilterUpdate
       * @param {number} arg1 - Go Type: interface {}
       * @returns {Promise<string>}  - Go Type: string
       */
      "FilterUpdate": (arg1) => {
        return window.go.main.App.FilterUpdate(arg1);
      },
      /**
       * GetFilters
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetFilters": () => {
        return window.go.main.App.GetFilters();
      },
      /**
       * GetLogs
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetLogs": () => {
        return window.go.main.App.GetLogs();
      },
      /**
       * GetStaticInfo
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetStaticInfo": () => {
        return window.go.main.App.GetStaticInfo();
      },
      /**
       * OpenArchive
       * @returns {Promise<string>}  - Go Type: string
       */
      "OpenArchive": () => {
        return window.go.main.App.OpenArchive();
      },
      /**
       * OpenFolder
       * @returns {Promise<string>}  - Go Type: string
       */
      "OpenFolder": () => {
        return window.go.main.App.OpenFolder();
      },
      /**
       * SetFilters
       * @param {any} arg1 - Go Type: map[string]bool
       * @returns {Promise<string>}  - Go Type: string
       */
      "SetFilters": (arg1) => {
        return window.go.main.App.SetFilters(arg1);
      },
      /**
       * UploadArchive
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "UploadArchive": (arg1) => {
        return window.go.main.App.UploadArchive(arg1);
      },
    },
  },

};
export default go;
